Выполнение задания спринта 9.
AlexanderAMedvedev/ImageFlow pull request #2
Opened 2023-06-23 21:55 UTC by AlexanderAMedvedev

2023-06-24 16:31 UTC, mmbabaev commented
Много ворнингов. Лучше относиться к ним как ошибкам, разобраться почему они появляются, исправлять их.

Здесь можно как вариант написать над функцией `@discardableResult`
<img width="787" alt="Screenshot 2023-06-24 at 19 29 09" src="https://github.com/AlexanderAMedvedev/imageFlowTable/assets/12600807/9554d71c-a396-4cc0-8437-a9d2ec17c595">

2023-06-24 16:37 UTC, mmbabaev commented
Отличается название файла картинки шаринга в storyboard и Asset. Из-за этого картинки кнопки нет
<img width="738" alt="Screenshot 2023-06-24 at 19 36 22" src="https://github.com/AlexanderAMedvedev/imageFlowTable/assets/12600807/139c3c26-2a12-492e-b7df-b819e9878259">

2023-06-24 16:40 UTC, mmbabaev requested changes

2023-06-24 16:40 UTC, mmbabaev commented on imageFlow/ImagesList/ImagesListViewController.swift
> +                //_ = viewController.view // CRASH FIXED !?
это не нужно? Наверное какой-то краш, связанный с тем, что view загружается лениво у UIViewController

2023-06-24 16:40 UTC, mmbabaev commented on imageFlow/ProfileViewController.swift
> +        addPersonalPhotoView()
лучше убрать ворнинги

2023-06-24 16:40 UTC, mmbabaev commented on imageFlow/ProfileViewController.swift
> +            with: UIImage(named: "ipad.and.arrow.forward")!,
лучше избегать форс анрапов

2023-06-24 16:40 UTC, mmbabaev commented on imageFlow/SingleImage/SingleImageViewController.swift
> +                guard isViewLoaded else { return }
не нужно оставлять закоментированный код в проекте, который сдаете на проверку

2023-06-24 16:40 UTC, mmbabaev commented on imageFlow/SingleImage/SingleImageViewController.swift
> +        // `present` - Presents a view controller modally.
лучше удалять учебные комментарии в проекте

2023-06-24 16:40 UTC, mmbabaev commented on imageFlow/SingleImage/SingleImageViewController.swift
> +        let activityView =  UIActivityViewController(activityItems: [image!], applicationActivities: nil)
лучше избегать форс анрапов

2023-06-27 15:48 UTC, AlexanderAMedvedev commented on imageFlow/ProfileViewController.swift
> +        addPersonalPhotoView()
Спасибо за совет по добавлению @discardableResult.

2023-06-27 15:54 UTC, AlexanderAMedvedev commented on imageFlow/ProfileViewController.swift
> +            with: UIImage(named: "ipad.and.arrow.forward")!,
Думал, что если обращаешься к объекту из Assets, то силовую распаковку можно применять.

2023-06-27 15:57 UTC, mmbabaev commented on imageFlow/ProfileViewController.swift
> +            with: UIImage(named: "ipad.and.arrow.forward")!,
их хотя бы в статические константы тогда положить можно

2023-06-27 16:30 UTC, AlexanderAMedvedev commented on imageFlow/SingleImage/SingleImageViewController.swift
> +                guard isViewLoaded else { return }
Убрал закомментированный код. Спасибо за совет!

2023-06-27 16:40 UTC, AlexanderAMedvedev commented on imageFlow/SingleImage/SingleImageViewController.swift
> +        // `present` - Presents a view controller modally.
Пока не буду их удалять, чтобы иметь объяснение в быстром доступе.

2023-06-27 18:49 UTC, AlexanderAMedvedev commented on imageFlow/ImagesList/ImagesListViewController.swift
> +                //_ = viewController.view // CRASH FIXED !?
Это не нужно. Удалил из кода.

2023-06-27 19:21 UTC, AlexanderAMedvedev commented on imageFlow/ProfileViewController.swift
> +            with: UIImage(named: "ipad.and.arrow.forward")!,
Имеете в виду код, написанный ниже?
```
class ProfileViewController: UIViewController {
static var exitImage = UIImage(named: "ipad.and.arrow.forward")!
...
}
```

2023-06-27 19:27 UTC, AlexanderAMedvedev commented on imageFlow/SingleImage/SingleImageViewController.swift
> +        let activityView =  UIActivityViewController(activityItems: [image!], applicationActivities: nil)
Внёс изменения в код. Ушёл от силовой распаковки.

2023-08-09 09:07 UTC, merged